import type { AnyPaystackOptions } from "./types";
declare const PAYSTACK_ERROR_CODES: {
    SUBSCRIPTION_NOT_FOUND: import("@better-auth/core/utils/error-codes").RawError<"SUBSCRIPTION_NOT_FOUND">;
    SUBSCRIPTION_PLAN_NOT_FOUND: import("@better-auth/core/utils/error-codes").RawError<"SUBSCRIPTION_PLAN_NOT_FOUND">;
    UNABLE_TO_CREATE_CUSTOMER: import("@better-auth/core/utils/error-codes").RawError<"UNABLE_TO_CREATE_CUSTOMER">;
    FAILED_TO_INITIALIZE_TRANSACTION: import("@better-auth/core/utils/error-codes").RawError<"FAILED_TO_INITIALIZE_TRANSACTION">;
    FAILED_TO_VERIFY_TRANSACTION: import("@better-auth/core/utils/error-codes").RawError<"FAILED_TO_VERIFY_TRANSACTION">;
    FAILED_TO_DISABLE_SUBSCRIPTION: import("@better-auth/core/utils/error-codes").RawError<"FAILED_TO_DISABLE_SUBSCRIPTION">;
    FAILED_TO_ENABLE_SUBSCRIPTION: import("@better-auth/core/utils/error-codes").RawError<"FAILED_TO_ENABLE_SUBSCRIPTION">;
    EMAIL_VERIFICATION_REQUIRED: import("@better-auth/core/utils/error-codes").RawError<"EMAIL_VERIFICATION_REQUIRED">;
};
export declare const paystackWebhook: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const initializeTransaction: <P extends string = "/paystack/initialize-transaction">(options: AnyPaystackOptions, path?: P) => StrictEndpoint<Path, Options, R>;
export declare const createSubscription: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const upgradeSubscription: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const restoreSubscription: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const cancelSubscription: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const verifyTransaction: <P extends string = "/paystack/verify-transaction">(options: AnyPaystackOptions, path?: P) => StrictEndpoint<Path, Options, R>;
export declare const listSubscriptions: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const listTransactions: <P extends string = "/paystack/list-transactions">(options: AnyPaystackOptions, path?: P) => StrictEndpoint<Path, Options, R>;
export declare const disablePaystackSubscription: <P extends string = "/paystack/disable-subscription">(options: AnyPaystackOptions, path?: P) => StrictEndpoint<Path, Options, R>;
export declare const enablePaystackSubscription: <P extends string = "/paystack/enable-subscription">(options: AnyPaystackOptions, path?: P) => StrictEndpoint<Path, Options, R>;
export declare const getSubscriptionManageLink: <P extends string = "/paystack/get-subscription-manage-link">(options: AnyPaystackOptions, path?: P) => StrictEndpoint<Path, Options, R>;
export declare const syncProducts: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const listProducts: (_options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const syncPlans: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const listPlans: (_options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export declare const getConfig: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
export { PAYSTACK_ERROR_CODES };
export declare const chargeRecurringSubscription: (options: AnyPaystackOptions) => StrictEndpoint<Path, Options, R>;
//# sourceMappingURL=routes.d.ts.map